# Generated by Django 4.2 on 2024-11-30 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('enq_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='アンケートタイトル')),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('format_id', models.IntegerField(primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=20, verbose_name='形式')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(verbose_name='質問')),
                ('order_no', models.IntegerField(default=0)),
                ('enq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enq.enquete')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enq.format')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=30, verbose_name='項目')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enq.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField(blank=True, max_length=300, null=True, verbose_name='アンケート結果')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enq.question')),
            ],
        ),
    ]
