# Generated by Django 4.2 on 2024-11-28 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('format_id', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=20, verbose_name='形式')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(verbose_name='質問')),
                ('order_id', models.IntegerField(default=0)),
                ('format_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enq.format')),
            ],
        ),
    ]
