# Generated by Django 4.2 on 2024-11-30 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_item', to='enq.question'),
        ),
    ]
