# Generated by Django 4.2 on 2024-11-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='order_id',
            new_name='order_no',
        ),
        migrations.AddField(
            model_name='question',
            name='enq_id',
            field=models.IntegerField(default=0, verbose_name='アンケート識別'),
        ),
    ]
