# Generated by Django 4.2 on 2024-11-29 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enq', '0002_rename_order_id_question_order_no_question_enq_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('enq_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='アンケートタイトル')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='enq_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enq.enquete'),
        ),
    ]
