# Generated by Django 4.2 on 2024-11-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enq', '0003_enquete_alter_question_enq_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='format_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
