# Generated by Django 4.2 on 2024-12-01 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enq', '0004_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='enq',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enq.enquete'),
        ),
    ]
