# Generated by Django 4.2 on 2024-11-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enq', '0005_item_question_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item1',
            field=models.CharField(default='非常に満足', max_length=100, verbose_name='項目1'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item2',
            field=models.CharField(default='やや満足', max_length=100, verbose_name='項目2'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item3',
            field=models.CharField(default='少し満足', max_length=100, verbose_name='項目3'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item4',
            field=models.CharField(default='どちらともいえない', max_length=100, verbose_name='項目4'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item5',
            field=models.CharField(default='少し不満', max_length=100, verbose_name='項目5'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item6',
            field=models.CharField(default='やや不満', max_length=100, verbose_name='項目6'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item7',
            field=models.CharField(default='非常に不満', max_length=100, verbose_name='項目7'),
        ),
    ]
