# Generated by Django 4.2 on 2024-11-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enq', '0007_answer_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(max_length=300, null=True, verbose_name='アンケート結果'),
        ),
    ]
